In [4]:
import pandas as pd
import numpy as np

po = pd.read_csv("loan.csv", encoding = "ANSI")
po

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
5,1075269,1311441,5000,5000,5000.00000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6,1069639,1304742,7000,7000,7000.00000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
7,1072053,1288686,3000,3000,3000.00000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
8,1071795,1306957,5600,5600,5600.00000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
9,1071570,1306721,5375,5375,5350.00000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
10,1070078,1305201,6500,6500,6500.00000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
11,1069908,1305008,12000,12000,12000.00000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12,1064687,1298717,9000,9000,9000.00000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13,1069866,1304956,3000,3000,3000.00000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14,1069057,1303503,10000,10000,10000.00000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,1069759,1304871,1000,1000,1000.00000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
16,1065775,1299699,10000,10000,10000.00000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
17,1069971,1304884,3600,3600,3600.00000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
18,1062474,1294539,6000,6000,6000.00000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19,1069742,1304855,9200,9200,9200.00000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
20,1069740,1284848,20250,20250,19142.16108,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
21,1039153,1269083,21000,21000,21000.00000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
22,1069710,1304821,10000,10000,10000.00000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
23,1069700,1304810,10000,10000,10000.00000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,1069559,1304634,6000,6000,6000.00000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
25,1069697,1273773,15000,15000,15000.00000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
26,1069800,1304679,15000,15000,8725.00000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
27,1069657,1304764,5000,5000,5000.00000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
28,1069799,1304678,4000,4000,4000.00000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
29,1047704,1278806,8500,8500,8500.00000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39687,111307,105982,12000,12000,2500.00000,36 months,12.49%,401.37,D,D3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39688,111227,111223,20000,20000,2800.00000,36 months,13.43%,678.08,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39689,109355,109346,1200,1200,0.00000,36 months,11.54%,39.60,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39690,107136,107130,12250,12250,1525.00000,36 months,10.59%,398.69,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39691,106360,106333,2700,2700,550.00000,36 months,15.96%,94.88,F,F4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39692,76597,76583,5000,5000,1775.00000,36 months,9.01%,159.03,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39693,106079,106039,3500,3500,1200.00000,36 months,9.96%,112.87,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39694,90966,90962,5000,5000,4150.00000,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39695,92440,92423,5000,5000,3100.00000,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39696,102376,95212,25000,25000,525.00000,36 months,10.59%,813.65,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39697,101579,100083,10000,10000,400.00000,36 months,10.28%,323.98,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39698,98982,98957,5000,5000,675.00000,36 months,9.01%,159.03,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39699,98339,97572,5100,5100,575.00000,36 months,8.38%,160.72,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39700,98276,98268,5400,5400,200.00000,36 months,7.75%,168.60,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39701,96844,95222,5300,5300,600.00000,36 months,8.38%,167.02,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39702,96350,96338,5000,5000,850.00000,36 months,11.22%,164.23,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39703,94838,73673,3000,3000,2550.00000,36 months,10.28%,97.20,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39704,93277,93254,3000,3000,950.00000,36 months,8.70%,94.98,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39705,93061,93057,5000,5000,250.00000,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39706,92676,92671,5000,5000,150.00000,36 months,8.07%,156.84,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39707,92666,92661,5000,5000,525.00000,36 months,9.33%,159.77,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39708,92552,92542,5000,5000,375.00000,36 months,9.96%,161.25,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39709,92533,92529,5000,5000,675.00000,36 months,11.22%,164.23,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39710,92507,92502,5000,5000,250.00000,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39711,92402,92390,5000,5000,700.00000,36 months,8.70%,158.30,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39712,92187,92174,2500,2500,1075.00000,36 months,8.07%,78.42,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39713,90665,90607,8500,8500,875.00000,36 months,10.28%,275.38,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39714,90395,90390,5000,5000,1325.00000,36 months,8.07%,156.84,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39715,90376,89243,5000,5000,650.00000,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39716,87023,86999,7500,7500,800.00000,36 months,13.75%,255.43,E,E2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
po.info()
po.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

(39717, 111)

In [ ]:
po = po.dropna(axis=1, how='all')
po.shape

In [ ]:
# FILLING NULL VALUES IN REVOL_UTIL WITH 0% SINCE MOST OF REVOL_BAL CORRESPONDING IS 0
po.dtypes
po['revol_util'].tail(20)
po[po['revol_util'].isnull()]
po.loc[po['revol_util'].isnull(), ['revol_util']] = "0%"
po['revol_util'].isnull().sum()

In [ ]:
#Converting int_rate column from string to float
po.int_rate = po.int_rate.apply(lambda x: x.replace('%',''))
po.int_rate = pd.to_numeric(po.int_rate)

In [ ]:
po.revol_util= po.revol_util.apply(lambda x: x.replace('%',''))
po.revol_util = pd.to_numeric(po.revol_util)

In [ ]:
po.revol_util

In [ ]:
po.loc[po.emp_length.isnull(),['emp_title','emp_length','annual_inc']]
po.emp_length = po.emp_length.apply(lambda x: x.replace(" years","") if x.notnull() else x)

In [ ]:
pochargedoff = po[po.loan_status == "Charged Off"]
pogood = po.loc[(po.loan_status == "Fully Paid") | (po.loan_status == "Current"), :]
pocurrent = po[po.loan_status == "Current"]
pogood

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# purp = pochargedoff.loc[:,["loan_status","purpose"]]

# plt.figure(figsize=(10, 6))

# plt.hist(po['purpose'])
# # plt.show()

In [ ]:
purp1 = pd.DataFrame(pochargedoff.purpose.value_counts())
purp1 = purp1.reset_index()
# plt.figure(figsize=(20, 6))
# sns.barplot(x = 'index',y='purpose',data=purp1)
# plt.show
# pochargedoff.purpose.value_counts()
purp1
pogood.purpose.value_counts()

In [ ]:
purp4 = pd.DataFrame(pochargedoff.grade.value_counts())
purp4 = purp4.reset_index()

In [ ]:
pochargedoff.loan_amnt.describe()

In [ ]:
pochargedoff.dti.describe()
pochargedoff['dti'].quantile(.95)

In [ ]:
# According to this dataset, dti is not a factor behind loan defaulting
pogood.dti.describe()
pogood['dti'].quantile(.95)

In [ ]:
pogood.loan_amnt.describe()

In [ ]:
pogood.installment.describe()

In [ ]:
pochargedoff.installment.describe()

In [ ]:
# SMALL BUSINESS HAS THE HIGHEST RATE OF DEFAULT

#purp2 = pd.DataFrame(pogood.purpose.value_counts())
# purp2 = purp2.reset_index()
# plt.figure(figsize=(20, 6))
# sns.barplot(x = 'index',y='purpose',data=purp2)
# plt.show()
po1 = pd.DataFrame(pogood.purpose.value_counts())
po1.rename(columns={'purpose':'total'}, inplace=True)
po1 = po1.reset_index()
po1
purpose_frame = pd.merge(purp1, po1, on='index', how='inner')
purpose_frame['percentage'] = round(100*(purpose_frame['purpose']/purpose_frame['total']))
purpose_frame.percentage

In [ ]:
po4 = pd.DataFrame(pogood.grade.value_counts())
po4.rename(columns={'grade':'total'}, inplace=True)
po4 = po4.reset_index()
po4
purpose_frame = pd.merge(purp4, po4, on='index', how='inner')
purpose_frame['percentage'] = round(100*(purpose_frame['grade']/purpose_frame['total']))
purpose_frame

In [ ]:
pochargedoff.int_rate.describe()

In [ ]:
pogood.int_rate.describe()

In [ ]:
pochargedoff[pochargedoff['revol_util'] == 0]

In [ ]:
pogood.revol_util.describe()
#pogood[pogood['revol_util'] == 0]

In [ ]:
pochargedoff.total_acc.describe()

In [ ]:
pogood.total_acc.describe()

In [ ]:
pochargedoff.open_acc.describe()

In [ ]:
pogood.open_acc.describe()

In [ ]:
pochargedoff[pochargedoff.verification_status == "Not Verified"]

In [ ]:
pogood[pogood.verification_status == "Not Verified"]

In [ ]:
pogood.pub_rec.sum()
pochargedoff.pub_rec.sum()

In [ ]:
pocurrent.shape
pocurrent.pub_rec.sum()
pocurrent.acc_now_delinq.sum()
pocurrent.chargeoff_within_12_mths.sum()
pocurrent.pub_rec_bankruptcies.sum()
pocurrent.tax_liens.sum()
pochargedoff.shape

In [ ]:
pochargedoff[pochargedoff.term == " 60 months"].shape

In [ ]:
pochargedoff.grade.value_counts()/5627

In [ ]:
pochargedoff.purpose.value_counts()/5627

In [ ]:
pochargedoff.home_ownership.value_counts()/5627

In [ ]:
pochargedoff.verification_status.value_counts()/5627

In [ ]:
pogood.revol_bal.describe()

In [ ]:
pochargedoff.revol_bal.describe()

In [ ]:
pochargedoff[pochargedoff.delinq_2yrs >= 1]